name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samuel19982/securepihole:latest
    - name: Login to registry
      run: docker login -u ${{secrets.USER}} -p ${{secrets.PASSWORD}}
    - name: Push the Docker image
      run: docker push samuel19982/securepihole:latest
